### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by seichris** [trustlines-protocol/clientlib-docs#7]
- exchange needs its own repo, so we can link it
- sidebar header: Clientlib Documentation
- generelles missverstaendnis ab
	Import UMD bundle in HTML
	<script src="./_bundles/trustlines-network.min.js"></script>
- kovan testnet wuerd ich etherscan linken.
	wenn nicht sogar alle (wieviele?) contract addresse listen in nem eigenen chapter
- guides heading#2
- eth-lightwallet keystore object. link missing?
- biggest representation?
- API heading#2
- linked sources are changing
https://docs.google.com/document/d/1T3ypymsJy8iJCefsimpf-pnpSz5kxIYbpN-Ks4ohZrA/edit#

**Comment by andfletcher** [comment]
Closing this issue since the documentation was redone.

**Comment by andfletcher** [comment]
@dakingha69 please reopen if you think this issue still needs attention
